project:
  machine_name: drupal.org.nz
  prefix: DRUPALNZ
  human_name: 'Drupal.org.nz - D8'
  profile:
    name: lightning
  local:
    protocol: http
    hostname: 'local.${project.machine_name}'
git:
  default_branch: develop
  remotes:
      - 'git@github.com:dman-coders/drupalorgnz.git'
drush:
  aliases:
    #remote: '${project.machine_name}.test'
    remote: 'live'
    local: self
    ci: self
  default_alias: '${drush.aliases.local}'
modules:
  local:
    enable: [dblog, devel, seckit, views_ui]
    uninstall: [acsf, acquia_connector, shield]
  ci:
    enable: {  }
    uninstall: [acquia_connector, shield]
  dev:
    enable: [acquia_connector, shield]
    uninstall: {  }
  test:
    enable: [acquia_connector, shield]
    uninstall: [devel, views_ui]
  prod:
    enable: [acquia_connector, shield]
    uninstall: [devel, views_ui]
